* Rag .emacs.d
Here is my emacs config.
** Notes
- This is a work in progress and is subject to frequent changes. Will be adding documentation for all the config files in due time.
- After playing around with helm for a month, I switched to a combination of Ivy + Swiper + Counsel largely due to how snappy and consistent they feel.
  If you want to use helm, comment out the following lines in =init.el= :-
  - =(require 'setup-ivy)=
  - =(require 'setup-counsel)=
  - =(require 'setup-swiper)=
  And after, add this line to =init.el= :- =(require 'setup-helm)=
- I run a very minimal theme with no toolbar, no scrollbars, no line numbers(I found emacs solution for line numbers to be lackluster, especially for handling long lines).
  I use ~PragmataPro~ as the preferred font and zenburn theme. These are all tuned for my preference, feel free to change them to your liking.
- Tested to work with emacs 25.1.1 on macOS, I only used emacs 24.5 for a month before shifting to emacs 25. Everything should work similarly, if any problem please report.

** Key points
- use of =use-package= for faster load times and loading packages only when necessary.
- Certain packages will only work if you have the associated applications installed
  - =ag= or =rg= [to generate projectile cache]
  - =git=    [for magit]
  - =ispell= [for spell check]
  - =racer=  [for rust completions]
  - =jedi=   [for python completions]
  - =LanguageTools= [for grammar check in org-mode]

* Feedback
Open to any feedback, corrections.
Thanks :)
