;; Time-stamp: <2016-12-01 11:42:29 csraghunandan>

;; view the list recently opened files
(use-package recentf
  :defer 1
  :config
  (recentf-mode 1)
  (setq recentf-max-menu-items 100)
  (setq recentf-max-saved-items 100)
  (setq recentf-exclude '("/elpa/" ;; ignore all files in elpa directory
                          ".*?autoloads.el$"
                          "company-statistics-cache.el" ;; ignore company cache file
                          "/intero/" ;; ignore script files generated by intero
                          "/journal/" ;; ignore daily journal files
                          ".gitignore" ;; ignore `.gitignore' files in projects
                          "loaddefs.el")))

(provide 'setup-recentf)
