;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple
;; cursors.

(setq mc/cmds-to-run-for-all
      '(
        counsel-M-x
        dired-mark
        eval-defun
        hungry-delete-backward
        hungry-delete-forward
        hydra-change-case/body
        hydra-change-case/modi/upcase-and-exit
        hydra-change-case/xah-cycle-letter-case
        indent-for-tab-command
        ivy-occur-delete-candidate
        ivy-wgrep-change-to-wgrep-mode
        kill-region
        mwim-beginning-of-code-or-line
        mwim-beginning-of-code-or-line-or-comment
        mwim-end-of-code-or-line
        org-beginning-of-line
        org-end-of-line
        org-metaright
        org-self-insert-command
        rag/kill-rectangle-replace-with-space
        recursive-widen
        sp-backward-delete-char
        sp-backward-kill-word
        sp-delete-char
        sp-kill-hybrid-sexp
        sp-kill-region
        sp-kill-sexp
        sp-kill-word
        sp-select-next-thing
        sp-strict-kill-line-or-region
        sp-unwrap-sexp
        wdired-finish-edit
        wgrep-finish-edit
        wrap-with-double-quotes
        ))

(setq mc/cmds-to-run-once
      '(
        counsel-grep-or-swiper
        ivy-done
        ))
